targets:
  $default:
    builders:
      freezed:
        options:
          union_key: type
          union_value_case: screaming_snake
      json_serializable:
        options:
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_field_map: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: snake
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
