name: homework_11
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  chopper: ^7.2.0
  cupertino_icons: ^1.0.6
  go_router: ^13.2.2
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  json_annotation: ^4.8.1
  loadmore: ^2.1.0
  provider: ^6.1.2
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  sqlite3_flutter_libs: ^0.5.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  build_runner: ^2.4.8
  chopper_generator: ^7.2.0
  golden_toolkit: ^0.15.0
  flutter_lints: ^3.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  assets: 
    - assets/
    - assets/images/
