// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjNhJ03v0cxwcyopkkrGe0AP8VpcSri_U',
    appId: '1:388505325913:web:9dc63fe94177f9592e7c48',
    messagingSenderId: '388505325913',
    projectId: 'homework-12-2c48b',
    authDomain: 'homework-12-2c48b.firebaseapp.com',
    storageBucket: 'homework-12-2c48b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY_7bzRaQZ5It5Z82A4yr6LzCPiVpAnhg',
    appId: '1:388505325913:android:76401ed52db89b292e7c48',
    messagingSenderId: '388505325913',
    projectId: 'homework-12-2c48b',
    storageBucket: 'homework-12-2c48b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7siyr9kaNdX4AiFdBuel4X21_y0f5KgQ',
    appId: '1:388505325913:ios:960d4301ea40b3652e7c48',
    messagingSenderId: '388505325913',
    projectId: 'homework-12-2c48b',
    storageBucket: 'homework-12-2c48b.appspot.com',
    iosBundleId: 'ru.mipt.homework12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7siyr9kaNdX4AiFdBuel4X21_y0f5KgQ',
    appId: '1:388505325913:ios:960d4301ea40b3652e7c48',
    messagingSenderId: '388505325913',
    projectId: 'homework-12-2c48b',
    storageBucket: 'homework-12-2c48b.appspot.com',
    iosBundleId: 'ru.mipt.homework12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjNhJ03v0cxwcyopkkrGe0AP8VpcSri_U',
    appId: '1:388505325913:web:6f2ff547e877b6b82e7c48',
    messagingSenderId: '388505325913',
    projectId: 'homework-12-2c48b',
    authDomain: 'homework-12-2c48b.firebaseapp.com',
    storageBucket: 'homework-12-2c48b.appspot.com',
  );
}
